name: BattleBuilders
main: Zade\BB
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
version: 5.0.0-Zade
author: Zadezter

commands:
    bb:
        usage: /bb <world>
        description: Create a new Battle Builders arena!
permissions:
    bb.op:
        default: op
  
